version: '3.7'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 'Maestro'

  web:
    build: .
    command: python /development/backend/siberian_engine/siberian_engine/siberian_engine/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/development/backend/siberian_engine/siberian_engine/siberian_engine
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
