version: '3.7'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - docker/env/.env.dev

  web:
    build: .
    command: python /development/backend/siberian_engine/siberian_engine/siberian_engine/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/development/backend/siberian_engine/siberian_engine/siberian_engine
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - docker/env/.env.dev

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
