name: SiberianEngine


on:
  push:
    branches:
      - master

jobs:
  check_pep:
    runs-on:  ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./siberian_engine/requirements.txt
      - name: Lint with Flake8
        run: flake8 --config=./siberian_engine/setup.cfg .

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Django CI
        uses: UKnowWhoIm/django-test-action@v0.6.1
        with:
          settings-dir-path: "siberian_engine/siberian_engine/"
          requirements-file: "siberian_engine/requirements.txt"
          env-file: "./siberian_engine/docker/env/.env.dev"
