# Generated by Django 4.2 on 2024-02-10 06:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "брэнд автомобиля",
                "verbose_name_plural": "брэнды автомобиля",
            },
        ),
        migrations.CreateModel(
            name="CategoryOperations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Название")),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.CreateModel(
            name="Engine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "count_of_cylinders",
                    models.IntegerField(default=0, verbose_name="Количество цилиндров"),
                ),
                (
                    "count_of_valves",
                    models.IntegerField(default=0, verbose_name="Количество клапанов"),
                ),
                (
                    "engine_type",
                    models.CharField(
                        choices=[("C", "Car"), ("TE", "Truck Engine")],
                        verbose_name="Тип двигателя",
                    ),
                ),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "двигатель",
                "verbose_name_plural": "двигатели",
            },
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=125, verbose_name="Название")),
                ("price", models.PositiveIntegerField(verbose_name="Цена")),
                ("slug", models.SlugField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.categoryoperations",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "engine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.engine",
                        verbose_name="Двигатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "операция",
                "verbose_name_plural": "операции",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "customer_name",
                    models.CharField(max_length=50, verbose_name="Имя заказчика"),
                ),
                (
                    "customer_phone_number",
                    models.CharField(max_length=12, verbose_name="Номер заказчика"),
                ),
                (
                    "total_amount",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Итоговая сумма"
                    ),
                ),
                (
                    "comments",
                    models.TextField(blank=True, null=True, verbose_name="Комментарии"),
                ),
                (
                    "accept_date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 2, 10, 6, 46, 58, 774967, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="Дата приёма",
                    ),
                ),
                (
                    "complete_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата выполнения"
                    ),
                ),
                (
                    "engine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.engine",
                    ),
                ),
                (
                    "operation",
                    models.ManyToManyField(
                        related_name="task",
                        to="core.operation",
                        verbose_name="Операция",
                    ),
                ),
            ],
            options={
                "verbose_name": "заказ",
                "verbose_name_plural": "заказы",
                "ordering": ["-accept_date"],
            },
        ),
        migrations.AddIndex(
            model_name="engine",
            index=models.Index(fields=["title"], name="core_engine_title_6e4a0e_idx"),
        ),
        migrations.AddIndex(
            model_name="engine",
            index=models.Index(
                fields=["engine_type"], name="core_engine_engine__f2b4cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="operation",
            index=models.Index(fields=["title"], name="core_operat_title_c79dcd_idx"),
        ),
        migrations.AddIndex(
            model_name="operation",
            index=models.Index(
                fields=["engine"], name="core_operat_engine__7df314_idx"
            ),
        ),
    ]
