# Generated by Django 4.2 on 2024-02-04 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('price', models.PositiveIntegerField()),
                ('slug', models.SlugField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=255)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_phone_number', models.CharField(max_length=12)),
                ('engine_title', models.CharField(max_length=50)),
                ('accept_date', models.DateTimeField(auto_now=True)),
                ('complete_date', models.DateTimeField()),
                ('complete_operation_date', models.DateTimeField()),
                ('count_of_cylinders', models.IntegerField(default=0)),
                ('count_of_valves', models.IntegerField(default=0)),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('operation', models.ManyToManyField(related_name='task', to='core.operation')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
