# Generated by Django 4.2 on 2024-02-10 06:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="engine",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.carbrand",
                verbose_name="Брэнд",
            ),
        ),
        migrations.AlterField(
            model_name="engine",
            name="engine_type",
            field=models.CharField(
                choices=[("TE", "Truck Engine"), ("C", "Car")],
                verbose_name="Тип двигателя",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="accept_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 10, 6, 51, 35, 804776, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата приёма",
            ),
        ),
    ]
