# Generated by Django 4.2 on 2024-02-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='complete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='complete_operation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
