# Generated by Django 4.2 on 2024-02-10 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_engine_brand_alter_engine_engine_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carbrand",
            name="title",
            field=models.CharField(max_length=50, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="engine",
            name="engine_type",
            field=models.CharField(
                choices=[("C", "Car"), ("TE", "Truck Engine")],
                verbose_name="Тип двигателя",
            ),
        ),
        migrations.AlterField(
            model_name="engine",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="order",
            name="accept_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 10, 9, 8, 9, 622652, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата приёма",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.AutoField(
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Номер заказа",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["id"], name="core_order_id_411167_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer_name"], name="core_order_custome_5cda00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["engine"], name="core_order_engine__0852e7_idx"),
        ),
    ]
