# Generated by Django 4.2 on 2024-02-19 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_carbrand_title_alter_engine_engine_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Принят", "Принят"),
                    ("В работе", "В работе"),
                    ("Готов", "Готов"),
                ],
                default=("В работе", "В работе"),
                verbose_name="Статус заказа",
            ),
        ),
        migrations.AlterField(
            model_name="engine",
            name="engine_type",
            field=models.CharField(
                choices=[("TE", "Truck Engine"), ("C", "Car")],
                verbose_name="Тип двигателя",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="accept_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 19, 12, 49, 23, 856953, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата приёма",
            ),
        ),
    ]
