# Generated by Django 4.2 on 2024-03-13 01:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_carbrand_options_alter_order_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_email",
            field=models.EmailField(
                blank=True, max_length=100, null=True, verbose_name="Почта"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="accept_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 13, 1, 11, 25, 107030, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата приёма",
            ),
        ),
    ]
