name: Check code

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        volumes:
          - postgres_data:/var/lib/postgresql/data/
        ports:
          - "5432:5432"
        env_file:
          - docker/env/.env.dev

      web:
        build: .
        command: python /development/backend/siberian_engine/siberian_engine/siberian_engine/manage.py test core.tests
        volumes:
          - .:/development/backend/siberian_engine/siberian_engine/siberian_engine
        ports:
          - "8000:8000"
        depends_on:
          - db
        env_file:
          - docker/env/.env.dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Docker Compose
        run: docker-compose up -d

      - name: Run Django tests
        run: docker-compose exec web python /development/backend/siberian_engine/siberian_engine/siberian_engine/manage.py test core.tests
