name: SiberianEngine


on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on:  ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./siberian_engine/requirements.txt
      - name: Lint with Flake8
        run: flake8 --config=./siberian_engine/setup.cfg .

  build_docker_image:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build
        run: docker-compose ./siberian_engine/docker-compose.yml up -d
      - name: Start tests
        run: docker-compose exec web python manage.py test core.tests