name: Foodgram


on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on:  ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./siberian_engine/requirements.txt
      - name: Go to
        run: cd siberian_engine
      - name: Lint with Flake8
        run: flake8 .